### PR TITLE
Added Lateef's Fact

### PR DESCRIPTION
**Pull request by lateefidris**

### CODE REVIEW

**Review by ajmompr — APPROVED** [review]
Hi Lateef! Looks good, although this is a mid/boring fact! Make sure to resolve conflicts before merging.

**Review by ciscovlahakis — APPROVED** [review]
Looks good!

**Review by ajmompr — CHANGES_REQUESTED** [review]
Looks good; can you fix the alignment?

**Review by ajmompr — APPROVED** [review]
Looks great!

**Review by ajmompr — APPROVED** [review]
Thanks for resolving conflicts

**Pull request merged**
