### PR TITLE
Added past experience regarding getting stuck in a different country

### PR DESCRIPTION
**Pull request by jeeheezy**

### CODE REVIEW

**Review by jpfababaer — APPROVED** [review]
This is cap.

**Review by andrewp8 — COMMENTED** [review]
Lesson learned. I want to hear more about that

**Comment by jeeheezy** [comment]
@jpfababaer Factual, not cap-tual. @andrewp8 can you approve in addition to comment?

**Review by andrewp8 — APPROVED** [review]

**Review by CarlosCastanedaDev — APPROVED** [review]
Good to go!

**Review by evolshenanigans — APPROVED** [review]
lgtm

**Pull request merged**
