### PR TITLE
kiowa's fun fact

### PR DESCRIPTION
**Pull request by kscott675**
kiowa is adding her fun fact

### CODE REVIEW

**Comment by jpfababaer** [comment]
gg

**Review by jpfababaer — APPROVED** [review]
I hate shrek.

**Review by reidaumann — APPROVED** [review]
I love Shrek too

**Comment by sera-11** [comment]
nice

**Review by jpfababaer — APPROVED** [review]
same

**Review by reidaumann — APPROVED** [review]

**Review by jpfababaer — APPROVED** [review]
seems about right

**Review by reidaumann — APPROVED** [review]

**Pull request merged**
