### PR TITLE
Added Reza's fun fact

### PR DESCRIPTION
**Pull request by rezahusain**

### CODE REVIEW

**Review by dylansarikas — CHANGES_REQUESTED** [review]
Add this `|` for correct formatting around your name and fun fact

**Review by APatel-AI — APPROVED** [review]
Looks Good 👍

**Review by reherr — APPROVED** [review]
looks even better!

**Review by rezahusain — COMMENTED** [review]
Looks fine

**Review by dylansarikas — APPROVED** [review]
Looks Good

**Pull request merged**
