### PR TITLE
added fun fact

### PR DESCRIPTION
**Pull request by EthanKH**

### CODE REVIEW

**Review by brendareyes-techprep — APPROVED** [review]
Hopefully you can merge now.

**Review by andrewhcook — APPROVED** [review]
That's very many!

**Review by chiucarman — APPROVED** [review]
wow which one is your fave?

**Review by AlinaSapronova — APPROVED** [review]

**Review by andrewhcook — APPROVED** [review]

**Review by AlinaSapronova — APPROVED** [review]

**Review by AlinaSapronova — APPROVED** [review]

**Comment by EthanKH** [comment]
> wow which one is your fave?

Twenty Five Twenty One!

**Pull request merged**
