### PR TITLE
Add cohort 2023-9.1

### PR DESCRIPTION
**Pull request by heratyian**

### CODE REVIEW

**Review by Dantexkilljoy — APPROVED** [review]
Sheesh 😮

**Comment by fidel-techprep** [comment]
it all looks beautiful

**Comment by aldoportillo** [comment]
We are missing a class nickname on line 30

**Review by alejlopez139 — APPROVED** [review]

**Review by fidel-techprep — APPROVED** [review]
Nice nice nice
niceeeeee

**Review by flstudio4 — APPROVED** [review]
Looks fine

**Review by ajmompr — APPROVED** [review]
This looks good

**Pull request merged**
