### PR TITLE
added my fun fact

### PR DESCRIPTION
**Pull request by MauritzKurt**
deleted template for new fact, added my own fact

### CODE REVIEW

**Review by dylansarikas — APPROVED** [review]
Looking Good!

**Review by hcontr4 — APPROVED** [review]
Nice!

**Review by hcontr4 — APPROVED** [review]
good

**Review by dylansarikas — APPROVED** [review]
Looks Good

**Review by hcontr4 — APPROVED** [review]

**Review by hcontr4 — APPROVED** [review]

**Review by aborov — APPROVED** [review]

**Review by aborov — APPROVED** [review]
love it!

**Review by dylansarikas — APPROVED** [review]
Looks good!

**Pull request merged**
