### PR TITLE
Added a fun fact about myself

### PR DESCRIPTION
**Pull request by prettyalana**

### CODE REVIEW

**Review by ctlio — APPROVED** [review]
Pink is such a pretty color! looks good to me!

**Review by DavidVLe1 — APPROVED** [review]
Looks Good!

**Review by ctlio — APPROVED** [review]

**Review by phamdvincent — APPROVED** [review]
Nice!

**Review by DavidVLe1 — APPROVED** [review]
looks good

**Review by phamdvincent — APPROVED** [review]

**Pull request merged**
