### PR TITLE
added Jared's nightshade fact

### PR DESCRIPTION
**Pull request by JaredBears**

### CODE REVIEW

**Review by fidel-techprep — APPROVED** [review]
Superb! You are hired!

**Review by thierrychau — APPROVED** [review]
Does that mean we shouldn't eat uncooked green peppers?

**Review by andrewhcook — APPROVED** [review]
I never knew!

**Review by ajmompr — APPROVED** [review]
Looks great

**Review by andrewhcook — APPROVED** [review]

**Comment by JaredBears** [comment]
> Does that mean we shouldn't eat uncooked green peppers?

Peppers have a very low level of toxicity, so they're fine, but if you eat a TON of them it can mess with your stomach.

**Pull request merged**
