### PR TITLE
Calvy's  funne fakte

### PR DESCRIPTION
**Pull request by armstrca**
Gaze upon my funne fakte, ye coederrs, and despair!!

### CODE REVIEW

**Review by thierrychau — APPROVED** [review]
wouhou!!

**Review by fidel-techprep — APPROVED** [review]
HIRED

**Review by melo616 — APPROVED** [review]
Fantastic

**Review by fidel-techprep — APPROVED** [review]

**Review by melo616 — APPROVED** [review]
Could be funner but ok

**Review by fidel-techprep — APPROVED** [review]

**Pull request merged**
