### PR TITLE
added fun fact

### PR DESCRIPTION
**Pull request by saraschoonover**

### CODE REVIEW

**Review by fidel-techprep — APPROVED** [review]
Hired!

**Review by JaredBears — APPROVED** [review]

**Review by andrewhcook — APPROVED** [review]

**Review by thierrychau — APPROVED** [review]
Great name!

**Review by fidel-techprep — APPROVED** [review]
yes!

**Review by fidel-techprep — APPROVED** [review]

**Review by andrewhcook — CHANGES_REQUESTED** [review]
Looks like Fidel is added twice!

**Review by fidel-techprep — APPROVED** [review]
YES

**Review by fidel-techprep — APPROVED** [review]
YES

**Review by fidel-techprep — APPROVED** [review]
YES

**Comment by saraschoonover** [comment]
Hey @andrewhcook I fixed those issues!

**Review by andrewhcook — COMMENTED** [review]
Looks good!

**Review by andrewhcook — APPROVED** [review]

**Review by andrewhcook — APPROVED** [review]

**Review by fidel-techprep — APPROVED** [review]
I SAID YESSSSSSSS 👍

**Pull request merged**
