### PR TITLE
added fun fact about David.

### PR DESCRIPTION
**Pull request by DavidVLe1**
added fun fact about David Le.

### CODE REVIEW

**Review by phamdvincent — APPROVED** [review]
Looks good!

**Review by jeeheezy — CHANGES_REQUESTED** [review]
Spacing needs work, thanks

**Review by phamdvincent — APPROVED** [review]
Nice!

**Review by jeeheezy — APPROVED** [review]
Looks better. Approved!

**Review by phamdvincent — APPROVED** [review]

**Pull request merged**
