### PR TITLE
Add fun fact

### PR DESCRIPTION
**Pull request by aldoportillo**
added fun fact!

### CODE REVIEW

**Review by JaredBears — APPROVED** [review]

**Review by flstudio4 — CHANGES_REQUESTED** [review]
too many blank lines

**Review by flstudio4 — APPROVED** [review]
ok, good!

**Review by fidel-techprep — APPROVED** [review]
HIRED!

**Comment by armstrca** [comment]
KILLIN THE GAME, ALDOOOOOOOOOOO

**Pull request merged**
