### PR TITLE
Added in my fun fact

### PR DESCRIPTION
**Pull request by WCW789**

### CODE REVIEW

**Review by flealc — COMMENTED** [review]
Hey! That is MY fun fact 😆

**Review by thierrychau — APPROVED** [review]
Looks good- maybe you just need to find your sport!

**Comment by CarlosCastanedaDev** [comment]
Looks good!

**Review by CarlosCastanedaDev — APPROVED** [review]

**Review by ajmompr — APPROVED** [review]
Looks good; please be sure to resolve conflicts before merging!

**Pull request merged**
